import localFont, { Inter } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter= Inter({subsets:["latin"]})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  antialiased`}
      >
        <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">

        {children}
        </main>
        <footer className="py-4 bg-blue-100">
          <div className="container text-center">
            <p>Made With 💖 by Nitin yadav</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
